# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mathfunc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mathfunc.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0emathfunc.proto\"!\n\x13\x46unctionDescription\x12\n\n\x02id\x18\x01 \x01(\x05\"C\n\x05State\x12\x12\n\nscheduling\x18\x01 \x01(\x08\x12\x11\n\tscheduled\x18\x02 \x01(\x08\x12\x13\n\x0bresultready\x18\x03 \x01(\x08\"\x08\n\x06\x44\x65lMsg\"\n\n\x08\x44\x65lState2[\n\x08MathFunc\x12/\n\rGuessFunction\x12\x14.FunctionDescription\x1a\x06.State\"\x00\x12\x1e\n\x06\x44\x65lete\x12\x07.DelMsg\x1a\t.DelState\"\x00\x62\x06proto3'
)




_FUNCTIONDESCRIPTION = _descriptor.Descriptor(
  name='FunctionDescription',
  full_name='FunctionDescription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='FunctionDescription.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=51,
)


_STATE = _descriptor.Descriptor(
  name='State',
  full_name='State',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='scheduling', full_name='State.scheduling', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='scheduled', full_name='State.scheduled', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resultready', full_name='State.resultready', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=120,
)


_DELMSG = _descriptor.Descriptor(
  name='DelMsg',
  full_name='DelMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=130,
)


_DELSTATE = _descriptor.Descriptor(
  name='DelState',
  full_name='DelState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=142,
)

DESCRIPTOR.message_types_by_name['FunctionDescription'] = _FUNCTIONDESCRIPTION
DESCRIPTOR.message_types_by_name['State'] = _STATE
DESCRIPTOR.message_types_by_name['DelMsg'] = _DELMSG
DESCRIPTOR.message_types_by_name['DelState'] = _DELSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FunctionDescription = _reflection.GeneratedProtocolMessageType('FunctionDescription', (_message.Message,), {
  'DESCRIPTOR' : _FUNCTIONDESCRIPTION,
  '__module__' : 'mathfunc_pb2'
  # @@protoc_insertion_point(class_scope:FunctionDescription)
  })
_sym_db.RegisterMessage(FunctionDescription)

State = _reflection.GeneratedProtocolMessageType('State', (_message.Message,), {
  'DESCRIPTOR' : _STATE,
  '__module__' : 'mathfunc_pb2'
  # @@protoc_insertion_point(class_scope:State)
  })
_sym_db.RegisterMessage(State)

DelMsg = _reflection.GeneratedProtocolMessageType('DelMsg', (_message.Message,), {
  'DESCRIPTOR' : _DELMSG,
  '__module__' : 'mathfunc_pb2'
  # @@protoc_insertion_point(class_scope:DelMsg)
  })
_sym_db.RegisterMessage(DelMsg)

DelState = _reflection.GeneratedProtocolMessageType('DelState', (_message.Message,), {
  'DESCRIPTOR' : _DELSTATE,
  '__module__' : 'mathfunc_pb2'
  # @@protoc_insertion_point(class_scope:DelState)
  })
_sym_db.RegisterMessage(DelState)



_MATHFUNC = _descriptor.ServiceDescriptor(
  name='MathFunc',
  full_name='MathFunc',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=144,
  serialized_end=235,
  methods=[
  _descriptor.MethodDescriptor(
    name='GuessFunction',
    full_name='MathFunc.GuessFunction',
    index=0,
    containing_service=None,
    input_type=_FUNCTIONDESCRIPTION,
    output_type=_STATE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Delete',
    full_name='MathFunc.Delete',
    index=1,
    containing_service=None,
    input_type=_DELMSG,
    output_type=_DELSTATE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MATHFUNC)

DESCRIPTOR.services_by_name['MathFunc'] = _MATHFUNC

# @@protoc_insertion_point(module_scope)
